version: 1.0.{build}

clone_depth: 1

configuration:
    - Release

os: Visual Studio 2019
image: Visual Studio 2019

platform:
    - x86
    - x64

environment:
    MEX: -DBUILD_MEX=OFF
    INSTALL_DIR: C:\projects\segyio-install
    TWINE_PASSWORD:
        secure: kTga6+rLL1fNpKqFNcX0QZNyqiYaHsEfSS4k6wvUoTE=
    matrix:
        - PYTHON: C:\Python36
          LANG: -DBUILD_PYTHON=ON
          PYTHON_VERSION: 36
        - PYTHON: C:\Python37
          LANG: -DBUILD_PYTHON=ON
          PYTHON_VERSION: 37
        - PYTHON: C:\Python38
          LANG: -DBUILD_PYTHON=ON
          PYTHON_VERSION: 38
        - PYTHON: C:\Python39
          LANG: -DBUILD_PYTHON=ON
          PYTHON_VERSION: 39

matrix:
    fast_finish: true

install:
    - git submodule update --init --recursive
    - IF DEFINED PYTHON (IF "%platform%" == "x64" SET PYTHON=%PYTHON%-x64)
    - IF DEFINED PYTHON SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - IF DEFINED PYTHON pip install -r requirements.txt
    - IF DEFINED PYTHON pip install --upgrade
        wheel
        setuptools
        setuptools-scm
        pytest
        pytest-runner
        scikit-build

    # updates in 0.12 make building 64-bit version on Appveyor fail
    - IF DEFINED PYTHON pip install scikit-build==0.11.0 --force-reinstall

before_build:
    - IF DEFINED PYTHON SET LANG=%LANG% -DPYTHON_EXECUTABLE=%PYTHON%\python
    - set generator="Visual Studio 14 2015"
    - IF "%platform%" == "x64" set generator="Visual Studio 14 2015 Win64"
    - git fetch --tags

build_script:
    - mkdir build
    - ps: pushd build
    - cmake %APPVEYOR_BUILD_FOLDER%
            -G %generator%
            %MEX%
            %LANG%
            -DCMAKE_CXX_FLAGS="/D_CRT_SECURE_NO_WARNINGS /EHsc"
    - cmake --build . --config "%configuration%" --target install
    - ctest -C "%configuration%" --output-on-failure
    - ps: popd
    - ps: pushd python
    - IF DEFINED PYTHON python setup.py bdist_wheel -G %generator%
    - ps: popd

test_script:
    - set PATH=%INSTALL_DIR%\bin;%PATH%
    - ps: pushd python
    - IF DEFINED PYTHON FOR /F "tokens=*" %%G IN ('dir /b dist\*.whl') DO
        pip install dist/%%G
    - ps: popd
    - IF DEFINED PYTHON python -c
        "import segyio;f=segyio.open('test-data/small.sgy');print(f.ilines)"
    - IF DEFINED PYTHON python python/examples/scan_min_max.py test-data/small.sgy
